### ISSUE TITLE
Доработать Dockerfile клиента для деплоя.

### ISSUE THREAD

**Issue by vedorofeev** [egal/nuxt-project#4]
Необходимо добавить nginx.conf в репозиторий и подключить его через Dockerfile для генерации статичных страниц.

**Comment by vedorofeev** [comment]
Также добавить в Dockerfile переменную, содержащую ссылку на API бэкенда

**Comment by rollsover** [comment]
https://github.com/egal/vue-project/pull/8
https://github.com/egal/nuxt-project/pull/5

**Comment by rollsover** [comment]
@Yulya-Yu билды не проходят, надо подшаманить сборку, у себя не получется

**Comment by Yulya-Yu** [comment]
Обновила версия Nuxt, подчистила от ненужного, локально сейчас билдится.

**Comment by rollsover** [comment]
Тут дубль https://github.com/egal/vue-project/issues/6
